// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: no_package_name_importer/no_package_name_importer.proto

package no_package_name_importer

import (
	no_package_name "github.com/livekit/psrpc/internal/test/no_package_name"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_no_package_name_importer_no_package_name_importer_proto protoreflect.FileDescriptor

const file_no_package_name_importer_no_package_name_importer_proto_rawDesc = "" +
	"\n" +
	"7no_package_name_importer/no_package_name_importer.proto\x1a%no_package_name/no_package_name.proto2\x1c\n" +
	"\x04Svc2\x12\x14\n" +
	"\x06Method\x12\x04.Msg\x1a\x04.MsgBAZ?github.com/livekit/psrpc/internal/test/no_package_name_importerb\x06proto3"

var file_no_package_name_importer_no_package_name_importer_proto_goTypes = []any{
	(*no_package_name.Msg)(nil), // 0: Msg
}
var file_no_package_name_importer_no_package_name_importer_proto_depIdxs = []int32{
	0, // 0: Svc2.Method:input_type -> Msg
	0, // 1: Svc2.Method:output_type -> Msg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_no_package_name_importer_no_package_name_importer_proto_init() }
func file_no_package_name_importer_no_package_name_importer_proto_init() {
	if File_no_package_name_importer_no_package_name_importer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_no_package_name_importer_no_package_name_importer_proto_rawDesc), len(file_no_package_name_importer_no_package_name_importer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_no_package_name_importer_no_package_name_importer_proto_goTypes,
		DependencyIndexes: file_no_package_name_importer_no_package_name_importer_proto_depIdxs,
	}.Build()
	File_no_package_name_importer_no_package_name_importer_proto = out.File
	file_no_package_name_importer_no_package_name_importer_proto_goTypes = nil
	file_no_package_name_importer_no_package_name_importer_proto_depIdxs = nil
}
