// Code generated by protoc-gen-psrpc v0.0.1, DO NOT EDIT.
// source: no_package_name_importer/no_package_name_importer.proto

package no_package_name_importer

import context "context"

import psrpc "github.com/livekit/psrpc"
import no_package_name "github.com/livekit/psrpc/internal/test/no_package_name"

// =====================
// Svc2 Client Interface
// =====================

type Svc2Client interface {
	Method(context.Context, *no_package_name.Msg, ...psrpc.RequestOpt) (*no_package_name.Msg, error)
}

// =========================
// Svc2 ServerImpl Interface
// =========================

type Svc2ServerImpl interface {
	Method(context.Context, *no_package_name.Msg) (*no_package_name.Msg, error)
}

// =====================
// Svc2 Server Interface
// =====================

type Svc2Server interface {
}

// ===========
// Svc2 Client
// ===========

type svc2Client struct {
	client psrpc.RPCClient
}

// NewSvc2Client creates a psrpc client that implements the Svc2Client interface.
func NewSvc2Client(clientID string, bus psrpc.MessageBus, opts ...psrpc.ClientOpt) (Svc2Client, error) {
	rpcClient, err := psrpc.NewRPCClient("Svc2", clientID, bus, opts...)
	if err != nil {
		return nil, err
	}

	return &svc2Client{
		client: rpcClient,
	}, nil
}

func (c *svc2Client) Method(ctx context.Context, req *no_package_name.Msg, opts ...psrpc.RequestOpt) (*no_package_name.Msg, error) {
	return psrpc.RequestTopicSingle[*no_package_name.Msg](ctx, c.client, "Method", "", req, opts...)
}

// ===========
// Svc2 Server
// ===========

type svc2Server struct {
	svc Svc2ServerImpl
	rpc psrpc.RPCServer
}

// NewSvc2Server builds a RPCServer that can be used to handle
// requests that are routed to the right method in the provided svc implementation.
func NewSvc2Server(serverID string, svc Svc2ServerImpl, bus psrpc.MessageBus, opts ...psrpc.ServerOpt) (Svc2Server, error) {
	rpcServer := psrpc.NewRPCServer("Svc2", serverID, bus, opts...)

	var err error
	err = rpcServer.RegisterHandler(psrpc.NewHandler("Method", svc.Method))
	if err != nil {
		rpcServer.Close()
		return nil, err
	}

	return &svc2Server{
		svc: svc,
		rpc: rpcServer,
	}, nil
}

var psrpcFileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcf, 0xcb, 0x8f, 0x2f,
	0x48, 0x4c, 0xce, 0x4e, 0x4c, 0x4f, 0x8d, 0xcf, 0x4b, 0xcc, 0x4d, 0x8d, 0xcf, 0xcc, 0x2d, 0xc8,
	0x2f, 0x2a, 0x49, 0x2d, 0xd2, 0xc7, 0x25, 0xa1, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0xa5, 0x8a,
	0x26, 0x8f, 0xae, 0x1e, 0xa2, 0xcc, 0x48, 0x86, 0x8b, 0x25, 0xb8, 0x2c, 0xd9, 0x48, 0x48, 0x84,
	0x8b, 0xcd, 0x37, 0xb5, 0x24, 0x23, 0x3f, 0x45, 0x88, 0x45, 0xcf, 0xb7, 0x38, 0x5d, 0x0a, 0x4c,
	0x3a, 0x39, 0x46, 0xd9, 0xa7, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0xe7,
	0x64, 0x96, 0xa5, 0x66, 0x67, 0x96, 0xe8, 0x17, 0x14, 0x17, 0x15, 0x24, 0xeb, 0x67, 0xe6, 0x95,
	0xa4, 0x16, 0xe5, 0x25, 0xe6, 0xe8, 0x97, 0xa4, 0x16, 0x97, 0xe0, 0x74, 0x4d, 0x12, 0x1b, 0xd8,
	0x1e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x62, 0x56, 0x40, 0xc9, 0x00, 0x00, 0x00,
}
