// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: importer.proto

// Test to make sure that importing other packages doesnt break

package importer

import (
	importable "github.com/livekit/psrpc/internal/test/importable"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_importer_proto protoreflect.FileDescriptor

const file_importer_proto_rawDesc = "" +
	"\n" +
	"\x0eimporter.proto\x12\x1cpsrpc.internal.test.importer\x1a\x10importable.proto2X\n" +
	"\x04Svc2\x12P\n" +
	"\x04Send\x12#.psrpc.internal.test.importable.Msg\x1a#.psrpc.internal.test.importable.MsgB1Z/github.com/livekit/psrpc/internal/test/importerb\x06proto3"

var file_importer_proto_goTypes = []any{
	(*importable.Msg)(nil), // 0: psrpc.internal.test.importable.Msg
}
var file_importer_proto_depIdxs = []int32{
	0, // 0: psrpc.internal.test.importer.Svc2.Send:input_type -> psrpc.internal.test.importable.Msg
	0, // 1: psrpc.internal.test.importer.Svc2.Send:output_type -> psrpc.internal.test.importable.Msg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_importer_proto_init() }
func file_importer_proto_init() {
	if File_importer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_importer_proto_rawDesc), len(file_importer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_importer_proto_goTypes,
		DependencyIndexes: file_importer_proto_depIdxs,
	}.Build()
	File_importer_proto = out.File
	file_importer_proto_goTypes = nil
	file_importer_proto_depIdxs = nil
}
