// Copyright 2023 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: my_service.proto

package my_service

import (
	_ "github.com/livekit/psrpc/protoc-gen-psrpc/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ignored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ignored) Reset() {
	*x = Ignored{}
	mi := &file_my_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ignored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ignored) ProtoMessage() {}

func (x *Ignored) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ignored.ProtoReflect.Descriptor instead.
func (*Ignored) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{0}
}

type MyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnError   int32                  `protobuf:"varint,1,opt,name=return_error,json=returnError,proto3" json:"return_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyRequest) Reset() {
	*x = MyRequest{}
	mi := &file_my_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyRequest) ProtoMessage() {}

func (x *MyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyRequest.ProtoReflect.Descriptor instead.
func (*MyRequest) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{1}
}

func (x *MyRequest) GetReturnError() int32 {
	if x != nil {
		return x.ReturnError
	}
	return 0
}

type MyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyResponse) Reset() {
	*x = MyResponse{}
	mi := &file_my_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyResponse) ProtoMessage() {}

func (x *MyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyResponse.ProtoReflect.Descriptor instead.
func (*MyResponse) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{2}
}

type MyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyUpdate) Reset() {
	*x = MyUpdate{}
	mi := &file_my_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUpdate) ProtoMessage() {}

func (x *MyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUpdate.ProtoReflect.Descriptor instead.
func (*MyUpdate) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{3}
}

type MyClientMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyClientMessage) Reset() {
	*x = MyClientMessage{}
	mi := &file_my_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyClientMessage) ProtoMessage() {}

func (x *MyClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyClientMessage.ProtoReflect.Descriptor instead.
func (*MyClientMessage) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{4}
}

type MyServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyServerMessage) Reset() {
	*x = MyServerMessage{}
	mi := &file_my_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyServerMessage) ProtoMessage() {}

func (x *MyServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_my_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyServerMessage.ProtoReflect.Descriptor instead.
func (*MyServerMessage) Descriptor() ([]byte, []int) {
	return file_my_service_proto_rawDescGZIP(), []int{5}
}

var File_my_service_proto protoreflect.FileDescriptor

const file_my_service_proto_rawDesc = "" +
	"\n" +
	"\x10my_service.proto\x12!psrpc.internal.test.customservice\x1a\roptions.proto\"\t\n" +
	"\aIgnored\".\n" +
	"\tMyRequest\x12!\n" +
	"\freturn_error\x18\x01 \x01(\x05R\vreturnError\"\f\n" +
	"\n" +
	"MyResponse\"\n" +
	"\n" +
	"\bMyUpdate\"\x11\n" +
	"\x0fMyClientMessage\"\x11\n" +
	"\x0fMyServerMessage2\xc4\x06\n" +
	"\tMyService\x12h\n" +
	"\tNormalRPC\x12,.psrpc.internal.test.customservice.MyRequest\x1a-.psrpc.internal.test.customservice.MyResponse\x12s\n" +
	"\fIntensiveRPC\x12,.psrpc.internal.test.customservice.MyRequest\x1a-.psrpc.internal.test.customservice.MyResponse\"\x06\xb2\x89\x01\x02@\x01\x12o\n" +
	"\bGetStats\x12,.psrpc.internal.test.customservice.MyRequest\x1a-.psrpc.internal.test.customservice.MyResponse\"\x06\xb2\x89\x01\x02@\x02\x12\x81\x01\n" +
	"\x0fExchangeUpdates\x122.psrpc.internal.test.customservice.MyClientMessage\x1a2.psrpc.internal.test.customservice.MyServerMessage\"\x06\xb2\x89\x01\x02 \x01\x12w\n" +
	"\x0eGetRegionStats\x12,.psrpc.internal.test.customservice.MyRequest\x1a-.psrpc.internal.test.customservice.MyResponse\"\b\xb2\x89\x01\x04\x10\x01@\x02\x12p\n" +
	"\rProcessUpdate\x12*.psrpc.internal.test.customservice.Ignored\x1a+.psrpc.internal.test.customservice.MyUpdate\"\x06\xb2\x89\x01\x02\b\x01\x12x\n" +
	"\x11UpdateRegionState\x12*.psrpc.internal.test.customservice.Ignored\x1a+.psrpc.internal.test.customservice.MyUpdate\"\n" +
	"\xb2\x89\x01\x06\b\x01\x10\x01@\x02B\rZ\v/my_serviceb\x06proto3"

var (
	file_my_service_proto_rawDescOnce sync.Once
	file_my_service_proto_rawDescData []byte
)

func file_my_service_proto_rawDescGZIP() []byte {
	file_my_service_proto_rawDescOnce.Do(func() {
		file_my_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_my_service_proto_rawDesc), len(file_my_service_proto_rawDesc)))
	})
	return file_my_service_proto_rawDescData
}

var file_my_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_my_service_proto_goTypes = []any{
	(*Ignored)(nil),         // 0: psrpc.internal.test.customservice.Ignored
	(*MyRequest)(nil),       // 1: psrpc.internal.test.customservice.MyRequest
	(*MyResponse)(nil),      // 2: psrpc.internal.test.customservice.MyResponse
	(*MyUpdate)(nil),        // 3: psrpc.internal.test.customservice.MyUpdate
	(*MyClientMessage)(nil), // 4: psrpc.internal.test.customservice.MyClientMessage
	(*MyServerMessage)(nil), // 5: psrpc.internal.test.customservice.MyServerMessage
}
var file_my_service_proto_depIdxs = []int32{
	1, // 0: psrpc.internal.test.customservice.MyService.NormalRPC:input_type -> psrpc.internal.test.customservice.MyRequest
	1, // 1: psrpc.internal.test.customservice.MyService.IntensiveRPC:input_type -> psrpc.internal.test.customservice.MyRequest
	1, // 2: psrpc.internal.test.customservice.MyService.GetStats:input_type -> psrpc.internal.test.customservice.MyRequest
	4, // 3: psrpc.internal.test.customservice.MyService.ExchangeUpdates:input_type -> psrpc.internal.test.customservice.MyClientMessage
	1, // 4: psrpc.internal.test.customservice.MyService.GetRegionStats:input_type -> psrpc.internal.test.customservice.MyRequest
	0, // 5: psrpc.internal.test.customservice.MyService.ProcessUpdate:input_type -> psrpc.internal.test.customservice.Ignored
	0, // 6: psrpc.internal.test.customservice.MyService.UpdateRegionState:input_type -> psrpc.internal.test.customservice.Ignored
	2, // 7: psrpc.internal.test.customservice.MyService.NormalRPC:output_type -> psrpc.internal.test.customservice.MyResponse
	2, // 8: psrpc.internal.test.customservice.MyService.IntensiveRPC:output_type -> psrpc.internal.test.customservice.MyResponse
	2, // 9: psrpc.internal.test.customservice.MyService.GetStats:output_type -> psrpc.internal.test.customservice.MyResponse
	5, // 10: psrpc.internal.test.customservice.MyService.ExchangeUpdates:output_type -> psrpc.internal.test.customservice.MyServerMessage
	2, // 11: psrpc.internal.test.customservice.MyService.GetRegionStats:output_type -> psrpc.internal.test.customservice.MyResponse
	3, // 12: psrpc.internal.test.customservice.MyService.ProcessUpdate:output_type -> psrpc.internal.test.customservice.MyUpdate
	3, // 13: psrpc.internal.test.customservice.MyService.UpdateRegionState:output_type -> psrpc.internal.test.customservice.MyUpdate
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_my_service_proto_init() }
func file_my_service_proto_init() {
	if File_my_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_my_service_proto_rawDesc), len(file_my_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_my_service_proto_goTypes,
		DependencyIndexes: file_my_service_proto_depIdxs,
		MessageInfos:      file_my_service_proto_msgTypes,
	}.Build()
	File_my_service_proto = out.File
	file_my_service_proto_goTypes = nil
	file_my_service_proto_depIdxs = nil
}
